### ISSUE TITLE
Scrutinizer error

### ISSUE THREAD

**Issue by Maikuolan** [alphazframework/framework#209]
Currently seeing this message from scrutinizer:

![composer](https://user-images.githubusercontent.com/12571108/55284191-214dce80-53a4-11e9-8f3f-8668be8444cd.png)

Not my area of expertise, so not something I could fix so easily, I think. Probably need to look more closely either at Composer package settings or at the unit tests, I think.

**Comment by peter279k** [comment]
@Maikuolan, thank you for your reply.

The Scrutinizer CI error due to the PHPUnit dependencies issue.

And I think we have the following suggestion to solve this:

- Let this package be `php:7.1` at least and define this about the `require` block in `composer.json`.
- Define the PHPUnit version to be `phpunit: "^7.0 || ^8.0"` about `require-dev` block so that this dependencies issue will be solved.

**Comment by lablnet** [comment]
@Maikuolan  thanks you so much for reporting the issue & @peter279k  thanks you for resolving..

**Comment by peter279k** [comment]
@Lablnet, do we need to support the `php-7.1` version?

Or require `php-7.2` version at least?

**Comment by lablnet** [comment]
`7.2`

**Comment by lablnet** [comment]
Because we use phpUnit version 8

**Comment by Maikuolan** [comment]
Sounds good. :-)
